In [1]:
import pandas

In [2]:
df=pandas.read_csv("GFDDData.csv")
df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
0,Afghanistan,AFG,5-bank asset concentration,GFDD.OI.06,NaN,NaN,NaN,NaN,NaN,NaN,...,89.3635,83.133,86.66470,84.8274,79.6688,86.60350,72.1549,71.9406,73.6723,NaN
1,Afghanistan,AFG,Account at a formal financial institution (% a...,GFDD.AI.05,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.00501,NaN,NaN,9.96100,NaN,NaN,14.5471,NaN
2,Afghanistan,AFG,Account used for business purposes (% age 15+),GFDD.AI.08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.71840,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,Account used to receive government payments (%...,GFDD.AI.09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Account used to receive remittances (% age 15+),GFDD.AI.10,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.25439,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25033,Zimbabwe,ZWE,Syndicated loan issuance volume to GDP (%),GFDD.DM.12,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25034,Zimbabwe,ZWE,Total factoring volume to GDP (%),GFDD.OI.18,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25035,Zimbabwe,ZWE,Value of collateral needed for a loan (% of th...,GFDD.AI.31,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,261.30000,NaN,NaN,NaN,NaN,223.4000,NaN,NaN
25036,Zimbabwe,ZWE,Value traded excluding top 10 traded companies...,GFDD.AM.01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25037,Zimbabwe,ZWE,Working capital financed by banks (%),GFDD.AI.35,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.50000,NaN,NaN,NaN,NaN,5.8000,NaN,NaN